<?php

/**
 * BaseSchool
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $name
 * @property enum $country
 * @property text $city
 * @property text $suburb
 * @property text $addr1
 * @property text $addr2
 * @property text $phone
 * @property text $email_address
 * @property text $website
 * @property text $leadingInstructor
 * @property text $classTime
 * @property boolean $isActive
 * @property Doctrine_Collection $Members
 * 
 * @method text                getName()              Returns the current record's "name" value
 * @method enum                getCountry()           Returns the current record's "country" value
 * @method text                getCity()              Returns the current record's "city" value
 * @method text                getSuburb()            Returns the current record's "suburb" value
 * @method text                getAddr1()             Returns the current record's "addr1" value
 * @method text                getAddr2()             Returns the current record's "addr2" value
 * @method text                getPhone()             Returns the current record's "phone" value
 * @method text                getEmailAddress()      Returns the current record's "email_address" value
 * @method text                getWebsite()           Returns the current record's "website" value
 * @method text                getLeadingInstructor() Returns the current record's "leadingInstructor" value
 * @method text                getClassTime()         Returns the current record's "classTime" value
 * @method boolean             getIsActive()          Returns the current record's "isActive" value
 * @method Doctrine_Collection getMembers()           Returns the current record's "Members" collection
 * @method School              setName()              Sets the current record's "name" value
 * @method School              setCountry()           Sets the current record's "country" value
 * @method School              setCity()              Sets the current record's "city" value
 * @method School              setSuburb()            Sets the current record's "suburb" value
 * @method School              setAddr1()             Sets the current record's "addr1" value
 * @method School              setAddr2()             Sets the current record's "addr2" value
 * @method School              setPhone()             Sets the current record's "phone" value
 * @method School              setEmailAddress()      Sets the current record's "email_address" value
 * @method School              setWebsite()           Sets the current record's "website" value
 * @method School              setLeadingInstructor() Sets the current record's "leadingInstructor" value
 * @method School              setClassTime()         Sets the current record's "classTime" value
 * @method School              setIsActive()          Sets the current record's "isActive" value
 * @method School              setMembers()           Sets the current record's "Members" collection
 * 
 * @package    ihs
 * @subpackage model
 * @author     leondeng <leondeng@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSchool extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('school');
        $this->hasColumn('name', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('country', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Australia',
              1 => 'Finnland',
              2 => 'USA',
              3 => 'Sri Lanka',
              4 => 'The Netherlands',
             ),
             ));
        $this->hasColumn('city', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('suburb', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('addr1', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('addr2', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('phone', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('email_address', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('website', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('leadingInstructor', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('classTime', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('isActive', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Profile as Members', array(
             'local' => 'id',
             'foreign' => 'idSchool'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}