<?php

/**
 * BaseSchool
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $name
 * @property enum $country
 * @property text $city
 * @property text $suburb
 * @property text $addr1
 * @property text $addr2
 * @property text $phone
 * @property text $email_address
 * @property text $website
 * @property text $leading_instructor
 * @property text $classtime
 * @property boolean $is_activated
 * @property Doctrine_Collection $Members
 * 
 * @method text                getName()               Returns the current record's "name" value
 * @method enum                getCountry()            Returns the current record's "country" value
 * @method text                getCity()               Returns the current record's "city" value
 * @method text                getSuburb()             Returns the current record's "suburb" value
 * @method text                getAddr1()              Returns the current record's "addr1" value
 * @method text                getAddr2()              Returns the current record's "addr2" value
 * @method text                getPhone()              Returns the current record's "phone" value
 * @method text                getEmailAddress()       Returns the current record's "email_address" value
 * @method text                getWebsite()            Returns the current record's "website" value
 * @method text                getLeadingInstructor()  Returns the current record's "leading_instructor" value
 * @method text                getClasstime()          Returns the current record's "classtime" value
 * @method boolean             getIsActivated()        Returns the current record's "is_activated" value
 * @method Doctrine_Collection getMembers()            Returns the current record's "Members" collection
 * @method School              setName()               Sets the current record's "name" value
 * @method School              setCountry()            Sets the current record's "country" value
 * @method School              setCity()               Sets the current record's "city" value
 * @method School              setSuburb()             Sets the current record's "suburb" value
 * @method School              setAddr1()              Sets the current record's "addr1" value
 * @method School              setAddr2()              Sets the current record's "addr2" value
 * @method School              setPhone()              Sets the current record's "phone" value
 * @method School              setEmailAddress()       Sets the current record's "email_address" value
 * @method School              setWebsite()            Sets the current record's "website" value
 * @method School              setLeadingInstructor()  Sets the current record's "leading_instructor" value
 * @method School              setClasstime()          Sets the current record's "classtime" value
 * @method School              setIsActivated()        Sets the current record's "is_activated" value
 * @method School              setMembers()            Sets the current record's "Members" collection
 * 
 * @package    ihs
 * @subpackage model
 * @author     leondeng <leondeng@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSchool extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('school');
        $this->hasColumn('name', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('country', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Australia',
              1 => 'Finnland',
              2 => 'USA',
              3 => 'Sri Lanka',
              4 => 'The Netherlands',
             ),
             ));
        $this->hasColumn('city', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('suburb', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('addr1', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('addr2', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('phone', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('email_address', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('website', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('leading_instructor', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('classtime', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Profile as Members', array(
             'local' => 'id',
             'foreign' => 'idSchool'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'city',
              1 => 'name',
             ),
             'unique' => false,
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}