<?php

/**
 * BaseProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property text $title
 * @property text $philosophy
 * @property date $dob
 * @property date $year_started
 * @property enum $belt_grade
 * @property boolean $is_instructor
 * @property integer $idUser
 * @property integer $idSchool
 * @property text $image_name
 * @property boolean $is_activated
 * @property sfGuardUser $User
 * @property School $School
 * 
 * @method string      getFirstName()     Returns the current record's "first_name" value
 * @method string      getLastName()      Returns the current record's "last_name" value
 * @method text        getTitle()         Returns the current record's "title" value
 * @method text        getPhilosophy()    Returns the current record's "philosophy" value
 * @method date        getDob()           Returns the current record's "dob" value
 * @method date        getYearStarted()   Returns the current record's "year_started" value
 * @method enum        getBeltGrade()     Returns the current record's "belt_grade" value
 * @method boolean     getIsInstructor()  Returns the current record's "is_instructor" value
 * @method integer     getIdUser()        Returns the current record's "idUser" value
 * @method integer     getIdSchool()      Returns the current record's "idSchool" value
 * @method text        getImageName()     Returns the current record's "image_name" value
 * @method boolean     getIsActivated()   Returns the current record's "is_activated" value
 * @method sfGuardUser getUser()          Returns the current record's "User" value
 * @method School      getSchool()        Returns the current record's "School" value
 * @method Profile     setFirstName()     Sets the current record's "first_name" value
 * @method Profile     setLastName()      Sets the current record's "last_name" value
 * @method Profile     setTitle()         Sets the current record's "title" value
 * @method Profile     setPhilosophy()    Sets the current record's "philosophy" value
 * @method Profile     setDob()           Sets the current record's "dob" value
 * @method Profile     setYearStarted()   Sets the current record's "year_started" value
 * @method Profile     setBeltGrade()     Sets the current record's "belt_grade" value
 * @method Profile     setIsInstructor()  Sets the current record's "is_instructor" value
 * @method Profile     setIdUser()        Sets the current record's "idUser" value
 * @method Profile     setIdSchool()      Sets the current record's "idSchool" value
 * @method Profile     setImageName()     Sets the current record's "image_name" value
 * @method Profile     setIsActivated()   Sets the current record's "is_activated" value
 * @method Profile     setUser()          Sets the current record's "User" value
 * @method Profile     setSchool()        Sets the current record's "School" value
 * 
 * @package    ihs
 * @subpackage model
 * @author     leondeng <leondeng@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('philosophy', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('dob', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('year_started', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('belt_grade', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Kup1',
              1 => 'Kup2',
              2 => 'Kup3',
              3 => 'Kup4',
              4 => 'Kup5',
              5 => 'Kup6',
              6 => 'Kup7',
              7 => 'Kup8',
              8 => 'Kup9',
             ),
             ));
        $this->hasColumn('is_instructor', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('idUser', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('idSchool', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('image_name', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'idUser',
             'foreign' => 'id'));

        $this->hasOne('School', array(
             'local' => 'idSchool',
             'foreign' => 'id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'first_name',
              1 => 'last_name',
             ),
             'unique' => false,
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}