<?php

/**
 * ProfileTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ProfileTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Profile');
  }

  public function getNextSlug() {
    $slug = Doctrine_Inflector::urlize(implode(' ', func_get_args()));
    $results = $this->createQuery('p')
      ->select('COUNT(p.slug) as max')
      ->addWhere('p.slug LIKE ?', trim($slug).'%')
      ->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
    if($results > 0) {
      $slug .= '-' . $results;
    }
    return $slug;
  }

}
