<?php

/**
 * Profile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ihs
 * @subpackage model
 * @author     leondeng <leondeng@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Profile extends BaseProfile
{
  public function getFullName() {
    return sprintf('%s %s %s', $this->getTitle(), $this->getFirstName(), $this->getLastName());
  }

  public function hasSchool() {
    return $this->getIdSchool() > 0;
  }

  public function getUniqueSlug() {
    return ProfileTable::getInstance()->getNextSlug($this->getFirstName(), $this->getLastName());
  }

}
