<?php

/**
 * SchoolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SchoolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SchoolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('School');
    }
}