<?php

/**
 * SchoolTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SchoolTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object SchoolTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('School');
  }

  public function getNextSlug() {
    $slug = Doctrine_Inflector::urlize(implode(' ', func_get_args()));
    $results = $this->createQuery('s')
      ->select('COUNT(s.slug) as max')
      ->addWhere('s.slug LIKE ?', trim($slug).'%')
      ->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
    if($results > 0) {
      $slug .= '-' . $results;
    }
    return $slug;
  }

}