<?php

/**
 * School
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ihs
 * @subpackage model
 * @author     leondeng <leondeng@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class School extends BaseSchool
{
  /* public function getLeadingInstructorObject() {
    $instructorName = $this->getLeadingInstructor();
    if(empty($instructorName)) return false;

    $slug = Doctrine_Inflector::urlize($instructorName);
    $instructor = ProfileTable::getInstance()->findOneBySlug($slug);

    if(!empty($instructor)) return $instructor;

    return false;
  } */

}
