# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:
all:
  google_maps_api:
    keys:
#      www.dimitristangl.com: AIzaSyACogY5GQp1FYxtYj9xk4ERdsvsvPhaEcw
#      ihs.localhost: AIzaSyACogY5GQp1FYxtYj9xk4ERdsvsvPhaEcw
#      default: AIzaSyACogY5GQp1FYxtYj9xk4ERdsvsvPhaEcw
      www.dimitristangl.com: AIzaSyAjSxV_0H-Zx3u8cuZJ-4n-GVYoTmF5288
      ihs.localhost: AIzaSyAjSxV_0H-Zx3u8cuZJ-4n-GVYoTmF5288
      default: AIzaSyAjSxV_0H-Zx3u8cuZJ-4n-GVYoTmF5288

  sf_guard_plugin:
    success_signin_url: @userAdmin
    success_signout_url: @homepage

  menus:
    admin_menu:
      name: Navigation
      children:
        home:
          label: HOME
          route: @homepage
#          requires_no_auth: true
        merchandise:
          label: MERCHANDISE
          route: @static?content=MerchandiseDVDSeries
          children:
            dvdseries:
              label: DVD Series
              route: @static?content=MerchandiseDVDSeries
#              requires_no_auth: true
            seperator1:
              label: |&nbsp;
              route: '#'
            danbong:
              label: IHA Dan Bong
              route: @static?content=MerchandiseIHADanBong
#              requires_no_auth: true
            seperator2:
              label: |&nbsp;
              route: '#'
            tshirt:
              label: T-Shirts
              route: @static?content=MerchandiseTShirts
#              requires_no_auth: true
        instructors:
          label: INSTRUCTORS
          route: @search_instructor
#          requires_no_auth: true
        forum:
          label: FORUM
          route: @static?content=forum
#          requires_no_auth: true
        knowledgebase:
          label: KNOWLEDGE BASE
          route: @static?content=knowledge_base
#          requires_no_auth: true
        dojang:
          label: DOJANG
          route: @search_dojang
#          requires_no_auth: true
        contact:
          label: CONTACT
          route: @static?content=contact_us
#          requires_no_auth: true
#        wikido:
#          label: WIKIKIDO
#          route: @static?content=wikikido
        