# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:
all:
  menus:
    admin_menu:
      name: Navigation
      children:
        home:
          label: HOME
          route: @homepage
          requires_no_auth: true
        merchandise:
          name: MERCHANDISE
          children:
            dvdseries:
              label: DVD SERIES
              route: @static?content=MerchandiseDVDSeries
              requires_no_auth: true
            danbong:
              label: IHA Dan Bong
              route: @static?content=MerchandiseIHADanBong
              requires_no_auth: true
            tshirt:
              label: T-Shirts
              route: @static?content=MerchandiseTShirts
              requires_no_auth: true
        instructors:
          label: INSTRUCTORS
          route: @static?content=instructorsearch
          requires_no_auth: true
        forum:
          label: FORUM
          route: @static?content=forum
          requires_no_auth: true
        knowledgebase:
          label: KNOWLEDGE BASE
          route: @static?content=knowlesgebase
          requires_no_auth: true
        dojang:
          label: DOJANG
          route: @static?content=dojangsearch
          requires_no_auth: true
          
#    admin_menu:
#      name:     Admin menu
#      children:
#        signin:
#          label:   Sign in
#          route:   @sf_guard_signin
#          requires_no_auth: true
#          attributes: {class: signin }
#        signout:
#          label:   Sign out
#          route:   @sf_guard_signout
#          requires_auth: true
#        user_admin:
#          label:          User Admin
#          requires_auth: true
#          children:
#            manage_users:
#              label:   Manage Users
#              route:   @sf_guard_user
#              credentials: [ManageUsers]
#            manage_permissions:
#              label:   Manage Permissions
#              route:   @sf_guard_permission
#              credentials: [ManagePermissions]
              