# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

userAdmin:
  url: /user_administration.:sf_format
  param:
    module: userAdmin
    action: index
    sf_format: html

change_password:
  url: /change_password.:sf_format
  param:
    module: userAdmin
    action: changePassword
    sf_format: html

change_email:
  url: /change_email.:sf_format
  param:
    module: userAdmin
    action: changeEmail
    sf_format: html

edit_profile:
  url: /edit_profile.:sf_format
  param:
    module: userAdmin
    action: editProfile
    sf_format: html

edit_school:
  url: /edit_dojang.:sf_format
  param:
    module: userAdmin
    action: editSchool
    sf_format: html

#userAdmin:
#  class: sfDoctrineRouteCollection
#  options:
#    type: object
#    model: sfGuardUser
#    prefix_path: /userAdmin
#    column: username
#    module: userAdmin
#    with_wildcard_routes: true
#    object_actions:
#      change_password: getObject
#      change_email: getObject
#      edit_profile: getObject
#      edit_school: getObject

search_instructor:
  url: /instructors.:sf_format
  param:
    module: search
    action: instructor
    sf_format: html

instructors_list:
  url: /instructors_result.:sf_format
  param:
    module: search
    action: searchInstructor
    sf_format: html

instructor:
  url: /blackbelt/:slug.:sf_format
  param:
    module: search
    action: viewInstructor
    sf_format: html
    
search_dojang:
  url: /dojang.:sf_format
  param:
    module: search
    action: dojang
    sf_format: html

dojang_list:
  url: /dojang_result.:sf_format
  param:
    module: search
    action: searchDojang
    sf_format: html

dojang:
  url: /dojang/:slug.:sf_format
  param:
    module: search
    action: viewDojang
    sf_format: html

# default rules
homepage:
  url:   /
  param:
    module: static
    action: index

sf_guard_signin:
  url:   /login.:sf_format
  param:
    module: sfGuardAuth
    action: signin
    sf_format: html

sf_guard_signout:
  url:   /logout.:sf_format
  param:
    module: sfGuardAuth
    action: signout
    sf_format: html

sf_guard_register:
  url:   /register.:sf_format
  param:
    module: register
    action: register
    sf_format: html

sf_guard_activate:
  url:   /active/:userid/:activation.:sf_format
  param:
    module: register
    action: activate
    sf_format: html

static:
  url: /:content.:sf_format
  param:
    module: static
    action: index
    sf_format: html

#sf_guard_password:
#  url:   /request_password.:sf_format
#  param:
#    module: sfGuardAuth
#    action: password
#    sf_format: html

#sf_guard_secure:
#  url:   /restricted.:sf_format
#  param:
#    module: sfGuardAuth
#    action: secure
#    sf_format: html

#change_password:
#  url: /change_password.:sf_format
#  param:
#    module: sfGuardAuth
#    action: changePassword
##    application: dashboard
#    sf_format: html

# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }

#default:
#  url:   /:module/:action/*
