actAs:
  Timestampable: ~

Profile:
  actAs:
    Sluggable:
      fields: [first_name, last_name]
      unique: false
      canUpdate: true
  columns:
    first_name: string(255)
#    middle_name: string(255)
    last_name: string(255)
#    email_address: string(255)
    title: text
    philosophy: text
    dob: date
    year_started: integer(4)
    belt_grade:
      type: enum
      values: [Kup1, Kup2, Kup3, Kup4, Kup5, Kup6, Kup7, Kup8, Kup9]
    is_instructor:
      type: boolean
      default: false
    idUser: integer
    idSchool: integer
    image_name: text
    is_publishable:
      type: boolean
      default: false
    token: string(32)
  relations:
    User:
      class: sfGuardUser
      local: idUser
      foreignType: one
      onDelete: CASCADE
    School:
      class: School
      local: idSchool
      foreign: id
      foreignAlias: Members

School:
  actAs:
    Sluggable:
      fields: [city, name]
      unique: false
      canUpdate: true
  columns:
    name: text
    country:
      type: enum
      values: [Australia, Finnland, USA, Sri Lanka, The Netherlands]
    city: text
    suburb: text
    addr1: text
    addr2: text
    phone: text
    email_address: text
    website: text
    leading_instructor: text
    classtime: text
    is_publishable:
      type: boolean
      default: false
    token: string(32)
